export const datas = [
  {
    id: 1,
    name: "Q1 Sales Report Processing",
    createdAt: new Date("2025-01-5"),
    status: "completed",
    currentStep: 4,
    files: { original: "sales_q1.xlsx", updated: "sales_q1_updated.xlsx" },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "updated",
      download: "ready",
    },
  },
  {
    id: 2,
    name: "Employee Data Migration",
    createdAt: new Date("2025-01-20"),
    status: "in_progress",
    currentStep: 2,
    files: { original: "employees.xlsx", updated: null },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "idle",
      download: "idle",
    },
  },
  // Add more sample tasks for pagination demo
  {
    id: 3,
    name: "Monthly Budget Analysis",
    createdAt: new Date("2025-01-18"),
    status: "completed",
    currentStep: 4,
    files: { original: "budget.xlsx", updated: "budget_updated.xlsx" },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "updated",
      download: "ready",
    },
  },
  {
    id: 4,
    name: "Customer Survey Results",
    createdAt: new Date("2025-01-22"),
    status: "in_progress",
    currentStep: 1,
    files: { original: null, updated: null },
    statuses: {
      task: "created",
      upload: "idle",
      update: "idle",
      download: "idle",
    },
  },
  {
    id: 5,
    name: "Inventory Management Update",
    createdAt: new Date("2025-01-19"),
    status: "in_progress",
    currentStep: 3,
    files: { original: "inventory.xlsx", updated: null },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "idle",
      download: "idle",
    },
  },
  {
    id: 6,
    name: "Product Catalog Sync",
    createdAt: new Date("2025-01-21"),
    status: "completed",
    currentStep: 4,
    files: { original: "catalog.xlsx", updated: "catalog_updated.xlsx" },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "updated",
      download: "ready",
    },
  },
  {
    id: 7,
    name: "HR Performance Review",
    createdAt: new Date("2025-01-17"),
    status: "in_progress",
    currentStep: 2,
    files: { original: "performance.xlsx", updated: null },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "idle",
      download: "idle",
    },
  },
  {
    id: 8,
    name: "Financial Quarterly Report",
    createdAt: new Date("2025-01-16"),
    status: "completed",
    currentStep: 4,
    files: { original: "quarterly.xlsx", updated: "quarterly_final.xlsx" },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "updated",
      download: "ready",
    },
  },
  {
    id: 9,
    name: "Marketing Campaign Data",
    createdAt: new Date("2025-01-23"),
    status: "in_progress",
    currentStep: 1,
    files: { original: null, updated: null },
    statuses: {
      task: "created",
      upload: "idle",
      update: "idle",
      download: "idle",
    },
  },
  {
    id: 10,
    name: "Sales Territory Analysis",
    createdAt: new Date("2025-01-14"),
    status: "completed",
    currentStep: 4,
    files: { original: "territory.xlsx", updated: "territory_analyzed.xlsx" },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "updated",
      download: "ready",
    },
  },
  {
    id: 11,
    name: "Vendor Contract Review",
    createdAt: new Date("2025-01-13"),
    status: "in_progress",
    currentStep: 3,
    files: { original: "contracts.xlsx", updated: null },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "idle",
      download: "idle",
    },
  },
  {
    id: 12,
    name: "Training Schedule Update",
    createdAt: new Date("2025-01-12"),
    status: "completed",
    currentStep: 4,
    files: { original: "training.xlsx", updated: "training_final.xlsx" },
    statuses: {
      task: "created",
      upload: "uploaded",
      update: "updated",
      download: "ready",
    },
  },
];
